### ISSUE TITLE
GET /v1/courses/sections does not conform to OpenAPI schema

### ISSUE THREAD

**Issue by DonIsaac** [umdio/umdio#211]
# Description

**Describe the bug**

`GET /v1/courses/sections` returns an array of an array of courses instead of an array of courses

**Provide the Endpoint**

`GET /v1/courses/sections`

**Expected Behavior**

It returns an array of course objects

**Actual Behavior**

It returns an array of an array of course objects

# Reproduction and Context

Literally just go to [the endpoint](https://api.umd.io/v1/courses/sections)

**Comment by Josiassejod1** [comment]
i threw the response from the endpoint in the json formatted and it seems to be okay and match the output of that of the Open Schema https://jsonformatter.curiousconcept.com/#

**Comment by tybug** [comment]
as above the response from the endpoint does seem valid to me, @DonIsaac can you double check / clarify your concerns?

![image](https://user-images.githubusercontent.com/31628143/122788193-154fcf00-d284-11eb-812a-9e1c3ba51955.png)

**Comment by DonIsaac** [comment]
> as above the response from the endpoint does seem valid to me, @DonIsaac can you double check / clarify your concerns?

```yaml
# openapi.yaml, line 979
semester:
  type: number
  example: 201501
  description: Numeric representation of the semester, in format YYYYMM
```

The semester number returned by the endpoint is a string.

Also, a good deal of these should be integers, not strings.
